/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author jaimedam
 */
public class frameCalculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameCalculadora.class.getName());

    /**
     * Creates new form frameCalculadora
     */
    public frameCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCalculadora = new javax.swing.JPanel();
        boton1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boton2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        boton3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        boton4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        boton5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        boton6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        boton7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        boton8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        boton9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        boton0 = new javax.swing.JPanel();
        jLabel0 = new javax.swing.JLabel();
        botonAC = new javax.swing.JPanel();
        jLabelAC = new javax.swing.JLabel();
        botonPorcentaje = new javax.swing.JPanel();
        jLabelPorcentaje = new javax.swing.JLabel();
        botonC = new javax.swing.JPanel();
        jLabelC = new javax.swing.JLabel();
        botonDividir = new javax.swing.JPanel();
        jLabelDividir = new javax.swing.JLabel();
        botonMultiplicar = new javax.swing.JPanel();
        jLabelMultiplicar = new javax.swing.JLabel();
        botonSumar = new javax.swing.JPanel();
        jLabelSumar = new javax.swing.JLabel();
        botonRestar = new javax.swing.JPanel();
        jLabelRestar = new javax.swing.JLabel();
        botonIgual = new javax.swing.JPanel();
        jLabelIgual = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelPantallaSalida = new javax.swing.JLabel();
        jLabelPantallaNum2 = new javax.swing.JLabel();
        jLabelPantallaNum1 = new javax.swing.JLabel();
        jLabelPantallaOperacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(385, 650));
        setResizable(false);

        panelCalculadora.setBackground(new java.awt.Color(49, 60, 103));
        panelCalculadora.setPreferredSize(new java.awt.Dimension(450, 650));

        boton1.setBackground(new java.awt.Color(165, 190, 247));
        boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton1MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 34, 179));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");
        jLabel1.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout boton1Layout = new javax.swing.GroupLayout(boton1);
        boton1.setLayout(boton1Layout);
        boton1Layout.setHorizontalGroup(
            boton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        boton1Layout.setVerticalGroup(
            boton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boton1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        boton2.setBackground(new java.awt.Color(165, 190, 247));
        boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton2MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 34, 179));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");
        jLabel2.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout boton2Layout = new javax.swing.GroupLayout(boton2);
        boton2.setLayout(boton2Layout);
        boton2Layout.setHorizontalGroup(
            boton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(boton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );
        boton2Layout.setVerticalGroup(
            boton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(boton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boton2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        boton3.setBackground(new java.awt.Color(165, 190, 247));
        boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton3MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 34, 179));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3");
        jLabel3.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout boton3Layout = new javax.swing.GroupLayout(boton3);
        boton3.setLayout(boton3Layout);
        boton3Layout.setHorizontalGroup(
            boton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(boton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );
        boton3Layout.setVerticalGroup(
            boton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(boton3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boton3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        boton4.setBackground(new java.awt.Color(165, 190, 247));
        boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton4MouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 34, 179));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4");
        jLabel4.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout boton4Layout = new javax.swing.GroupLayout(boton4);
        boton4.setLayout(boton4Layout);
        boton4Layout.setHorizontalGroup(
            boton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(boton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );
        boton4Layout.setVerticalGroup(
            boton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(boton4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boton4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        boton5.setBackground(new java.awt.Color(165, 190, 247));
        boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton5MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 34, 179));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");
        jLabel5.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout boton5Layout = new javax.swing.GroupLayout(boton5);
        boton5.setLayout(boton5Layout);
        boton5Layout.setHorizontalGroup(
            boton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(boton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );
        boton5Layout.setVerticalGroup(
            boton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(boton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boton5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        boton6.setBackground(new java.awt.Color(165, 190, 247));
        boton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton6MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 34, 179));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("6");
        jLabel6.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout boton6Layout = new javax.swing.GroupLayout(boton6);
        boton6.setLayout(boton6Layout);
        boton6Layout.setHorizontalGroup(
            boton6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(boton6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );
        boton6Layout.setVerticalGroup(
            boton6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(boton6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boton6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        boton7.setBackground(new java.awt.Color(165, 190, 247));
        boton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton7MouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(52, 34, 179));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("7");
        jLabel7.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout boton7Layout = new javax.swing.GroupLayout(boton7);
        boton7.setLayout(boton7Layout);
        boton7Layout.setHorizontalGroup(
            boton7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(boton7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );
        boton7Layout.setVerticalGroup(
            boton7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(boton7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boton7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        boton8.setBackground(new java.awt.Color(165, 190, 247));
        boton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton8MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(52, 34, 179));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("8");
        jLabel8.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout boton8Layout = new javax.swing.GroupLayout(boton8);
        boton8.setLayout(boton8Layout);
        boton8Layout.setHorizontalGroup(
            boton8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(boton8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );
        boton8Layout.setVerticalGroup(
            boton8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(boton8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boton8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        boton9.setBackground(new java.awt.Color(165, 190, 247));
        boton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton9MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(52, 34, 179));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("9");
        jLabel9.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout boton9Layout = new javax.swing.GroupLayout(boton9);
        boton9.setLayout(boton9Layout);
        boton9Layout.setHorizontalGroup(
            boton9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(boton9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );
        boton9Layout.setVerticalGroup(
            boton9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(boton9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boton9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        boton0.setBackground(new java.awt.Color(165, 190, 247));
        boton0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton0MouseExited(evt);
            }
        });

        jLabel0.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel0.setForeground(new java.awt.Color(52, 34, 179));
        jLabel0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0.setText("0");
        jLabel0.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabel0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel0MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout boton0Layout = new javax.swing.GroupLayout(boton0);
        boton0.setLayout(boton0Layout);
        boton0Layout.setHorizontalGroup(
            boton0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(boton0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );
        boton0Layout.setVerticalGroup(
            boton0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(boton0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(boton0Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel0, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        botonAC.setBackground(new java.awt.Color(165, 190, 247));
        botonAC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonACMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonACMouseExited(evt);
            }
        });

        jLabelAC.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelAC.setForeground(new java.awt.Color(52, 34, 179));
        jLabelAC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAC.setText("AC");
        jLabelAC.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabelAC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelACMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonACLayout = new javax.swing.GroupLayout(botonAC);
        botonAC.setLayout(botonACLayout);
        botonACLayout.setHorizontalGroup(
            botonACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
            .addGroup(botonACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabelAC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
        );
        botonACLayout.setVerticalGroup(
            botonACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(botonACLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonACLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelAC, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        botonPorcentaje.setBackground(new java.awt.Color(165, 190, 247));
        botonPorcentaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonPorcentajeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonPorcentajeMouseExited(evt);
            }
        });

        jLabelPorcentaje.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelPorcentaje.setForeground(new java.awt.Color(52, 34, 179));
        jLabelPorcentaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPorcentaje.setText("%");
        jLabelPorcentaje.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabelPorcentaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPorcentajeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonPorcentajeLayout = new javax.swing.GroupLayout(botonPorcentaje);
        botonPorcentaje.setLayout(botonPorcentajeLayout);
        botonPorcentajeLayout.setHorizontalGroup(
            botonPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
            .addGroup(botonPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabelPorcentaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
        );
        botonPorcentajeLayout.setVerticalGroup(
            botonPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(botonPorcentajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonPorcentajeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelPorcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        botonC.setBackground(new java.awt.Color(165, 190, 247));
        botonC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCMouseExited(evt);
            }
        });

        jLabelC.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabelC.setForeground(new java.awt.Color(52, 34, 179));
        jLabelC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelC.setText("C");
        jLabelC.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabelC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonCLayout = new javax.swing.GroupLayout(botonC);
        botonC.setLayout(botonCLayout);
        botonCLayout.setHorizontalGroup(
            botonCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
            .addGroup(botonCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabelC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
        );
        botonCLayout.setVerticalGroup(
            botonCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(botonCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonCLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelC, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        botonDividir.setBackground(new java.awt.Color(165, 190, 247));
        botonDividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonDividirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonDividirMouseExited(evt);
            }
        });

        jLabelDividir.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabelDividir.setForeground(new java.awt.Color(52, 34, 179));
        jLabelDividir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDividir.setText("/");
        jLabelDividir.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabelDividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDividirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonDividirLayout = new javax.swing.GroupLayout(botonDividir);
        botonDividir.setLayout(botonDividirLayout);
        botonDividirLayout.setHorizontalGroup(
            botonDividirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(botonDividirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabelDividir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );
        botonDividirLayout.setVerticalGroup(
            botonDividirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(botonDividirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonDividirLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelDividir, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        botonMultiplicar.setBackground(new java.awt.Color(165, 190, 247));
        botonMultiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMultiplicarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMultiplicarMouseExited(evt);
            }
        });

        jLabelMultiplicar.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabelMultiplicar.setForeground(new java.awt.Color(52, 34, 179));
        jLabelMultiplicar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMultiplicar.setText("x");
        jLabelMultiplicar.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabelMultiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMultiplicarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonMultiplicarLayout = new javax.swing.GroupLayout(botonMultiplicar);
        botonMultiplicar.setLayout(botonMultiplicarLayout);
        botonMultiplicarLayout.setHorizontalGroup(
            botonMultiplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(botonMultiplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabelMultiplicar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );
        botonMultiplicarLayout.setVerticalGroup(
            botonMultiplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(botonMultiplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonMultiplicarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelMultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        botonSumar.setBackground(new java.awt.Color(165, 190, 247));
        botonSumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSumarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSumarMouseExited(evt);
            }
        });

        jLabelSumar.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabelSumar.setForeground(new java.awt.Color(52, 34, 179));
        jLabelSumar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSumar.setText("+");
        jLabelSumar.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabelSumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSumarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonSumarLayout = new javax.swing.GroupLayout(botonSumar);
        botonSumar.setLayout(botonSumarLayout);
        botonSumarLayout.setHorizontalGroup(
            botonSumarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(botonSumarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabelSumar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );
        botonSumarLayout.setVerticalGroup(
            botonSumarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(botonSumarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonSumarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelSumar, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        botonRestar.setBackground(new java.awt.Color(165, 190, 247));
        botonRestar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRestarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRestarMouseExited(evt);
            }
        });

        jLabelRestar.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabelRestar.setForeground(new java.awt.Color(52, 34, 179));
        jLabelRestar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRestar.setText("-");
        jLabelRestar.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabelRestar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRestarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonRestarLayout = new javax.swing.GroupLayout(botonRestar);
        botonRestar.setLayout(botonRestarLayout);
        botonRestarLayout.setHorizontalGroup(
            botonRestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(botonRestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabelRestar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );
        botonRestarLayout.setVerticalGroup(
            botonRestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(botonRestarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonRestarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelRestar, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        botonIgual.setBackground(new java.awt.Color(165, 190, 247));
        botonIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonIgualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonIgualMouseExited(evt);
            }
        });

        jLabelIgual.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabelIgual.setForeground(new java.awt.Color(52, 34, 179));
        jLabelIgual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIgual.setText("=");
        jLabelIgual.setPreferredSize(new java.awt.Dimension(15, 30));
        jLabelIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIgualMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonIgualLayout = new javax.swing.GroupLayout(botonIgual);
        botonIgual.setLayout(botonIgualLayout);
        botonIgualLayout.setHorizontalGroup(
            botonIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(botonIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabelIgual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );
        botonIgualLayout.setVerticalGroup(
            botonIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(botonIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonIgualLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelIgual, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
        );

        jLabel10.setBackground(new java.awt.Color(165, 190, 247));
        jLabel10.setFont(new java.awt.Font("Nimbus Mono PS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(165, 190, 247));
        jLabel10.setText("CALCULADORA DISEÑO WEB | 2º DAM");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelPantallaSalida.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPantallaSalida.setFont(new java.awt.Font("Nimbus Sans", 1, 24)); // NOI18N
        jLabelPantallaSalida.setForeground(new java.awt.Color(52, 34, 179));
        jLabelPantallaSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPantallaSalida.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabelPantallaNum2.setFont(new java.awt.Font("Nimbus Sans", 1, 18)); // NOI18N
        jLabelPantallaNum2.setForeground(new java.awt.Color(52, 34, 179));
        jLabelPantallaNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelPantallaNum1.setFont(new java.awt.Font("Nimbus Sans", 1, 18)); // NOI18N
        jLabelPantallaNum1.setForeground(new java.awt.Color(52, 34, 179));
        jLabelPantallaNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelPantallaOperacion.setFont(new java.awt.Font("Nimbus Sans", 1, 18)); // NOI18N
        jLabelPantallaOperacion.setForeground(new java.awt.Color(52, 34, 179));
        jLabelPantallaOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelPantallaNum2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(jLabelPantallaNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabelPantallaOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelPantallaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabelPantallaNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPantallaOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabelPantallaNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabelPantallaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelCalculadoraLayout = new javax.swing.GroupLayout(panelCalculadora);
        panelCalculadora.setLayout(panelCalculadoraLayout);
        panelCalculadoraLayout.setHorizontalGroup(
            panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalculadoraLayout.createSequentialGroup()
                .addGroup(panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCalculadoraLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCalculadoraLayout.createSequentialGroup()
                                .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCalculadoraLayout.createSequentialGroup()
                                .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCalculadoraLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCalculadoraLayout.createSequentialGroup()
                                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botonRestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCalculadoraLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCalculadoraLayout.createSequentialGroup()
                                .addComponent(botonAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(botonC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(botonPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelCalculadoraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelCalculadoraLayout.setVerticalGroup(
            panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalculadoraLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRestar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCalculadora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseEntered
        boton1.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_boton1MouseEntered

    private void boton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MouseEntered
        boton2.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_boton2MouseEntered

    private void boton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3MouseEntered
        boton3.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_boton3MouseEntered

    private void boton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MouseEntered
        boton4.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_boton4MouseEntered

    private void boton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton5MouseEntered
        boton5.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_boton5MouseEntered

    private void boton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton6MouseEntered
        boton6.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_boton6MouseEntered

    private void boton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton7MouseEntered
        boton7.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_boton7MouseEntered

    private void boton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton8MouseEntered
        boton8.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_boton8MouseEntered

    private void boton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton9MouseEntered
        boton9.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_boton9MouseEntered

    private void boton0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton0MouseEntered
        boton0.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_boton0MouseEntered

    private void botonACMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonACMouseEntered
        botonAC.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_botonACMouseEntered

    private void botonPorcentajeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPorcentajeMouseEntered
        botonPorcentaje.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_botonPorcentajeMouseEntered

    private void botonCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCMouseEntered
        botonC.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_botonCMouseEntered

    private void botonDividirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDividirMouseEntered
        botonDividir.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_botonDividirMouseEntered

    private void botonMultiplicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMultiplicarMouseEntered
        botonMultiplicar.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_botonMultiplicarMouseEntered

    private void botonSumarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSumarMouseEntered
        botonSumar.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_botonSumarMouseEntered

    private void botonRestarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRestarMouseEntered
        botonRestar.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_botonRestarMouseEntered

    private void botonIgualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIgualMouseEntered
        botonIgual.setBackground(new Color(142, 174, 246));
    }//GEN-LAST:event_botonIgualMouseEntered

    private void boton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseExited
        boton1.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_boton1MouseExited

    private void boton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MouseExited
        boton2.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_boton2MouseExited

    private void boton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3MouseExited
        boton3.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_boton3MouseExited

    private void boton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MouseExited
        boton4.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_boton4MouseExited

    private void boton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton5MouseExited
        boton5.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_boton5MouseExited

    private void boton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton6MouseExited
        boton6.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_boton6MouseExited

    private void boton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton7MouseExited
        boton7.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_boton7MouseExited

    private void boton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton8MouseExited
        boton8.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_boton8MouseExited

    private void boton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton9MouseExited
        boton9.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_boton9MouseExited

    private void boton0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton0MouseExited
        boton0.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_boton0MouseExited

    private void botonACMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonACMouseExited
        botonAC.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_botonACMouseExited

    private void botonCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCMouseExited
        botonC.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_botonCMouseExited

    private void botonPorcentajeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPorcentajeMouseExited
        botonPorcentaje.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_botonPorcentajeMouseExited

    private void botonDividirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDividirMouseExited
        botonDividir.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_botonDividirMouseExited

    private void botonMultiplicarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMultiplicarMouseExited
        botonMultiplicar.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_botonMultiplicarMouseExited

    private void botonSumarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSumarMouseExited
        botonSumar.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_botonSumarMouseExited

    private void botonRestarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRestarMouseExited
        botonRestar.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_botonRestarMouseExited

    private void botonIgualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIgualMouseExited
        botonIgual.setBackground(new Color(165,190,247));
    }//GEN-LAST:event_botonIgualMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        if(jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaNum1.setText(jLabelPantallaNum1.getText() + "1");
        }else if(jLabelPantallaSalida.getText().isEmpty()){
        jLabelPantallaNum2.setText(jLabelPantallaNum2.getText() + "1");
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        if(jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaNum1.setText(jLabelPantallaNum1.getText() + "2");
        }else if(jLabelPantallaSalida.getText().isEmpty()){
        jLabelPantallaNum2.setText(jLabelPantallaNum2.getText() + "2");
        }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
        if(jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaNum1.setText(jLabelPantallaNum1.getText() + "3");
        }else if(jLabelPantallaSalida.getText().isEmpty()){
        jLabelPantallaNum2.setText(jLabelPantallaNum2.getText() + "3");
        }
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        if(jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaNum1.setText(jLabelPantallaNum1.getText() + "4");
        }else if(jLabelPantallaSalida.getText().isEmpty()){
        jLabelPantallaNum2.setText(jLabelPantallaNum2.getText() + "4");
        }
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        
        if(jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaNum1.setText(jLabelPantallaNum1.getText() + "5");
        }else if(jLabelPantallaSalida.getText().isEmpty()){
        jLabelPantallaNum2.setText(jLabelPantallaNum2.getText() + "5");
        }
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        
        if(jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaNum1.setText(jLabelPantallaNum1.getText() + "6");
        }else if(jLabelPantallaSalida.getText().isEmpty()){
        jLabelPantallaNum2.setText(jLabelPantallaNum2.getText() + "6");
        }
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        
        if(jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaNum1.setText(jLabelPantallaNum1.getText() + "7");
        }else if(jLabelPantallaSalida.getText().isEmpty()){
        jLabelPantallaNum2.setText(jLabelPantallaNum2.getText() + "7");
        }
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        
        if(jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaNum1.setText(jLabelPantallaNum1.getText() + "8");
        }else if(jLabelPantallaSalida.getText().isEmpty()){
        jLabelPantallaNum2.setText(jLabelPantallaNum2.getText() + "8");
        }
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        
        if(jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaNum1.setText(jLabelPantallaNum1.getText() + "9");
        }else if(jLabelPantallaSalida.getText().isEmpty()){
        jLabelPantallaNum2.setText(jLabelPantallaNum2.getText() + "9");
        }
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel0MouseClicked
        
       if(jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaNum1.setText(jLabelPantallaNum1.getText() + "0");
        }else if(jLabelPantallaSalida.getText().isEmpty()){
        jLabelPantallaNum2.setText(jLabelPantallaNum2.getText() + "0");
        } 
               
    }//GEN-LAST:event_jLabel0MouseClicked

    private void jLabelACMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelACMouseClicked
        resetearPantalla();
    }//GEN-LAST:event_jLabelACMouseClicked

    private void jLabelCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCMouseClicked
        
        /*if(jLabelPantallaOperacion.getText().isEmpty()){
            quitarUltimoDigitoPantallaNum1();
        }else{
            quitarUltimoDigitoPantallaNum2();
        } */
        
    }//GEN-LAST:event_jLabelCMouseClicked

    private void jLabelDividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDividirMouseClicked
        
        if( !jLabelPantallaNum1.getText().isEmpty() && jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaOperacion.setText(jLabelDividir.getText());
        }
        
    }//GEN-LAST:event_jLabelDividirMouseClicked

    private void jLabelMultiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMultiplicarMouseClicked
        
        if(!jLabelPantallaNum1.getText().isEmpty() && jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaOperacion.setText(jLabelMultiplicar.getText());
        }
        
    }//GEN-LAST:event_jLabelMultiplicarMouseClicked

    private void jLabelSumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSumarMouseClicked
        
        if(!jLabelPantallaNum1.getText().isEmpty() && jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaOperacion.setText(jLabelSumar.getText());
        }
        
    }//GEN-LAST:event_jLabelSumarMouseClicked

    private void jLabelRestarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRestarMouseClicked
        
        if(!jLabelPantallaNum1.getText().isEmpty() && jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaOperacion.setText(jLabelRestar.getText());
        }
        
    }//GEN-LAST:event_jLabelRestarMouseClicked

    private void jLabelPorcentajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPorcentajeMouseClicked
        
        if(!jLabelPantallaNum1.getText().isEmpty() && jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaOperacion.setText(jLabelPorcentaje.getText());
        }
        
    }//GEN-LAST:event_jLabelPorcentajeMouseClicked

    private void jLabelIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIgualMouseClicked
        
        if (!jLabelPantallaNum1.getText().isEmpty() && !jLabelPantallaNum2.getText().isEmpty() && !jLabelPantallaOperacion.getText().isEmpty()) {
            realizarOperacion();
        }
        
    }//GEN-LAST:event_jLabelIgualMouseClicked

    
    private void realizarOperacion(){
        
        double num1 = Double.parseDouble(jLabelPantallaNum1.getText());
        double num2 = Double.parseDouble(jLabelPantallaNum2.getText());
        
        double resultado;
        
        String operacion = jLabelPantallaOperacion.getText();
        
        if (operacion.equals("%")) {
            resultado = ((num2 * num1)/100);
            
            jLabelPantallaSalida.setText(String.valueOf(resultado)); 
        }
        else if(operacion.equals("/")){
            if (num2 == 0) {
                jLabelPantallaSalida.setText("Sin definir");
            }else{
                resultado = num1 / num2;
                
                jLabelPantallaSalida.setText(String.valueOf(resultado));
            }
        }
        else if(operacion.equals("x")){
            resultado = num1 * num2;
            
            jLabelPantallaSalida.setText(String.valueOf(resultado));
        }
        else if(operacion.equals("+")){
            resultado = num1 + num2;
            
            jLabelPantallaSalida.setText(String.valueOf(resultado));
        }
        else if(operacion.equals("-")){
            resultado = num1 - num2;
            
            jLabelPantallaSalida.setText(String.valueOf(resultado));
        }
        
    }
    
    private void resetearPantalla(){
        
        jLabelPantallaNum1.setText("");
        jLabelPantallaNum2.setText("");
        jLabelPantallaOperacion.setText("");
        jLabelPantallaSalida.setText("");
        
    }
    
    /*private void quitarUltimoDigitoPantallaNum1() {
        String textoPantallaNum1 = jLabelPantallaNum1.getText();
        ArrayList<String> numeros1 = new ArrayList<>();

        // Pasar cada numero al ArrayList
        for (int i = 0; i < textoPantallaNum1.length(); i++) {
            numeros1.add(String.valueOf(textoPantallaNum1.charAt(i)));
        }

        // Borrar el último si hay algo
        if (!numeros1.isEmpty()) {
            numeros1.remove(numeros1.size() - 1);
        }

        // Reconstruir el texto y actualizar el JLabel
        jLabelPantallaNum1.setText(String.join("", numeros1));
    }*/

    
    
    /*private void jLabelSumarMouseClicked(java.awt.event.MouseEvent evt) {                                         
        if(jLabelPantallaOperacion.getText().isEmpty()){
            jLabelPantallaOperacion.setText(jLabelSumar.getText());
        }
    }*/ 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frameCalculadora().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boton0;
    private javax.swing.JPanel boton1;
    private javax.swing.JPanel boton2;
    private javax.swing.JPanel boton3;
    private javax.swing.JPanel boton4;
    private javax.swing.JPanel boton5;
    private javax.swing.JPanel boton6;
    private javax.swing.JPanel boton7;
    private javax.swing.JPanel boton8;
    private javax.swing.JPanel boton9;
    private javax.swing.JPanel botonAC;
    private javax.swing.JPanel botonC;
    private javax.swing.JPanel botonDividir;
    private javax.swing.JPanel botonIgual;
    private javax.swing.JPanel botonMultiplicar;
    private javax.swing.JPanel botonPorcentaje;
    private javax.swing.JPanel botonRestar;
    private javax.swing.JPanel botonSumar;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAC;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelDividir;
    private javax.swing.JLabel jLabelIgual;
    private javax.swing.JLabel jLabelMultiplicar;
    private javax.swing.JLabel jLabelPantallaNum1;
    private javax.swing.JLabel jLabelPantallaNum2;
    private javax.swing.JLabel jLabelPantallaOperacion;
    private javax.swing.JLabel jLabelPantallaSalida;
    private javax.swing.JLabel jLabelPorcentaje;
    private javax.swing.JLabel jLabelRestar;
    private javax.swing.JLabel jLabelSumar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelCalculadora;
    // End of variables declaration//GEN-END:variables
}
